server:
  port: 8090
spring:
  rabbitmq:
#    addresses: amqp://admin:secret@localhost:
    host: 172.17.0.2
    port: 5672
    username: guest
    password: guest
#    stream:
#      name: stream1
    template:
      retry:
        enabled: true
        initial-interval: 10s
#      default-receive-queue: queue1